/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

/**
 *
 * @author Julian
 */
public class frmPrincipalUsuarios extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipalUsuarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txUsuarioActual = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        mArchivo = new javax.swing.JMenu();
        mnCuenta = new javax.swing.JMenuItem();
        mnSalir = new javax.swing.JMenuItem();
        mMantenimiento = new javax.swing.JMenu();
        mnUsuarios = new javax.swing.JMenuItem();
        mnClientes = new javax.swing.JMenuItem();
        mnProveedores = new javax.swing.JMenuItem();
        mnProductos = new javax.swing.JMenuItem();
        mConsumos = new javax.swing.JMenu();
        mnGenerarConsumo = new javax.swing.JMenuItem();
        mnVerConsumos = new javax.swing.JMenuItem();
        mOrdenes = new javax.swing.JMenu();
        mnGenOrden = new javax.swing.JMenuItem();
        mnVerOrdenes = new javax.swing.JMenuItem();
        mAyuda = new javax.swing.JMenu();
        mnAcercaDe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tienda Smart - Admins");

        jLabel1.setText("Usuario:");

        txUsuarioActual.setEditable(false);
        txUsuarioActual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txUsuarioActualActionPerformed(evt);
            }
        });

        mArchivo.setText("Archivo");

        mnCuenta.setText("Cuenta");
        mArchivo.add(mnCuenta);

        mnSalir.setText("Salir");
        mArchivo.add(mnSalir);

        jMenuBar1.add(mArchivo);

        mMantenimiento.setText("Mantenimiento");

        mnUsuarios.setText("Usuarios");
        mMantenimiento.add(mnUsuarios);

        mnClientes.setText("Clientes");
        mMantenimiento.add(mnClientes);

        mnProveedores.setText("Proveedores");
        mMantenimiento.add(mnProveedores);

        mnProductos.setText("Productos");
        mMantenimiento.add(mnProductos);

        jMenuBar1.add(mMantenimiento);

        mConsumos.setText("Consumo");

        mnGenerarConsumo.setText("Nuevo Consumo");
        mConsumos.add(mnGenerarConsumo);

        mnVerConsumos.setText("Ver Consumos");
        mConsumos.add(mnVerConsumos);

        jMenuBar1.add(mConsumos);

        mOrdenes.setText("Proveedores");

        mnGenOrden.setText("Generar Orden");
        mOrdenes.add(mnGenOrden);

        mnVerOrdenes.setText("Ver Ordenes Proveedores");
        mOrdenes.add(mnVerOrdenes);

        jMenuBar1.add(mOrdenes);

        mAyuda.setText("Ayuda");

        mnAcercaDe.setText("Acerca De...");
        mAyuda.add(mnAcercaDe);

        jMenuBar1.add(mAyuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txUsuarioActual, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(435, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(336, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txUsuarioActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txUsuarioActualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txUsuarioActualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txUsuarioActualActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mArchivo;
    private javax.swing.JMenu mAyuda;
    private javax.swing.JMenu mConsumos;
    private javax.swing.JMenu mMantenimiento;
    private javax.swing.JMenu mOrdenes;
    private javax.swing.JMenuItem mnAcercaDe;
    private javax.swing.JMenuItem mnClientes;
    private javax.swing.JMenuItem mnCuenta;
    private javax.swing.JMenuItem mnGenOrden;
    private javax.swing.JMenuItem mnGenerarConsumo;
    private javax.swing.JMenuItem mnProductos;
    private javax.swing.JMenuItem mnProveedores;
    private javax.swing.JMenuItem mnSalir;
    private javax.swing.JMenuItem mnUsuarios;
    private javax.swing.JMenuItem mnVerConsumos;
    private javax.swing.JMenuItem mnVerOrdenes;
    private javax.swing.JTextField txUsuarioActual;
    // End of variables declaration//GEN-END:variables
}
